Update release_tag.yml

diff --git a/.github/workflows/release_tag.yml b/.github/workflows/release_tag.yml
--- a/.github/workflows/release_tag.yml
+++ b/.github/workflows/release_tag.yml
@@ -1,28 +1,35 @@
 name: Release Tag
 
-#트리거 요소
-
+# 트리거 조건
 on: 
   pull_request:
     branches:
       - production
     types:
       - closed
-    paths:
-      - 'release/**'
-
+  
 jobs:
   build:
     runs-on: ubuntu-latest
     steps:
+    # 1. 저장소 체크아웃
     - uses: actions/checkout@v2
+    
+    # 2. 커밋 메시지에서 버전 정보 추출
     - name: 버전 정보 추출
-      run: echo "##[set-output name=version;]$(echo '${{ github.ref }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')"
       id: extract_version_name
-    - name: Release 생성 
+      run: |
+        VERSION=$(echo '${{ github.event.pull_request.title }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
+        if [ -z "$VERSION" ]; then
+          echo "Error: No version number found in pull request title." && exit 1
+        fi
+        echo "VERSION=$VERSION" >> $GITHUB_ENV
+
+    # 3. Release 생성
+    - name: Release 생성
       uses: actions/create-release@v1
-      env: 
+      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with: 
-        tag_name: ${{ steps.extract_version_name.outputs.version }} 
-        release_name: ${{ steps.extract_version_name.outputs.version }} 
+      with:
+        tag_name: ${{ env.VERSION }}
+        release_name: ${{ env.VERSION }}
